version: '3'

services:
  # PostgreSQL for Keystone
  postgres_autho:
    image: postgres:13
    container_name: postgres_autho
    environment:
      POSTGRES_USER: autho_user
      POSTGRES_PASSWORD: autho_pass
      POSTGRES_DB: autho_db
    ports:
      - "5432:5432"  # Keystone DB exposed on 5432
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - openstack

  # PostgreSQL for Authentication Service
  postgres_auth:
    image: postgres:13
    container_name: postgres_auth
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"  # Auth DB exposed on 5433 (inside container it's still 5432)
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - openstack

  # Redis for Barbican caching/queue management
  redis:
    image: redis:6
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    networks:
      - openstack

networks:
  openstack:
    driver: bridge

volumes:
  pgdata_keystone:  # Volume for Keystone DB
  pgdata_auth:      # Volume for Authentication DB
  redisdata:        # Volume for Redis data
